#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     IRfront,        sensorNone)
#pragma config(Sensor, S2,     IRright,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SONAR,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "turing_constants.c"

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

}

///////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();
	//waitForStart();  // Wait for the beginning of autonomous phase

	// Find center goal position using front IR.
	if (SensorValue[S1]==5 || SensorValue[S1]==3 || SensorValue[S1]==0) {
		// Center goal is pointed at floor goal (0 degrees)
		if (SensorValue[S1]==5) {
			// Drive at center goal.
			motor[motorH]=50;
			motor[motorI]=-50;
			wait1Msec(2500);
			// Turn 90 degrees counterclockwise to line up with IRright.
			while (SensorValue[S2]!=5) {
				motor[motorH]=100;
				motor[motorI]=100;
			}
			motor[motorH]=0;
			motor[motorI]=0;
			// Dump balls with auto arm.

		}
		// Center goal is pointed at opponent's rolling goals. (45 degrees)
		if (SensorValue[S1]==3) {
			// Drive toward center goal.
			motor[motorH]=50;
			motor[motorI]=-50;
			wait1Msec(2250);
			// Turn 45 degrees counterclockwise to line up with IRright.
			while (SensorValue[S2] != 3) {
				motor[motorH]=100;
				motor[motorI]=100;
			}
			motor[motorH]=0;
			motor[motorI]=0;
			// Dump balls with auto arm.

		}
		// Center goal is pointed between opponent's ramp and opponent's rolling goals. (90 degrees)
		if (SensorValue[S1]==0) {
			// Drive toward center goal.
			motor[motorH]=50;
			motor[motorI]=-50;
			wait1Msec(2500);
			// Turn 45 deg counterclockwise
			motor[motorH]=100;
			motor[motorI]=100;
			wait1Msec(1400);
			motor[motorH]=50;
			motor[motorI]=-50;
			wait1Msec(3180);
			// Turn 45 deg clockwise
			motor[motorH]=-100;
			motor[motorI]=-100;
			wait1Msec(1400);
			// Stop when IRright value is strong.
			while (SensorValue[S2] != 5) {
				motor[motorH]=50;
				motor[motorI]=-50;
			}
			motor[motorH]=0;
			motor[motorI]=0;
			// Dump balls with auto arm.

		}
		// Start heading to the kickstand -- back up a teeny bit.
		motor[motorH]=-50;
		motor[motorI]=50;
		// Turn 90 degrees counterclockwise.
		motor[motorH]=50;
		motor[motorI]=50;
		wait1Msec(2800);
		// Dead reckon backwards, into the kickstand.
		motor[motorH]=-100;
		motor[motorI]=100;
		wait1Msec(4000);
	}
}
