#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     IRfront,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     IRright,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SONAR,          sensorSONAR)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "turing_constants.c"
#include "JoystickDriver.c"

void initializeRobot()
{
	servo[servo1] = AUTO_ARM_STARTING_POSITION;
	servo[servo3] = 0;
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

}

///////////////////////////////////////////////////////////////////////////////////////////////////////

task main() {
	initializeRobot();

	motor[motorH] = 100;
	motor[motorI] = -100;
	wait1Msec(10000);
	motor[motorH] = 0;
	motor[motorI] = 0;
}
