#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     TOUCH,          sensorTouch)
#pragma config(Sensor, S3,     SONAR,          sensorSONAR)
#pragma config(Sensor, S4,     LIGHT,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is the setup for the IR and touch sensors, S1/S2 are the ports
// they're plugged into, don't change anything else.

// Diagnostics 101
// 2012 VHS FTC

task main()
{
  nxtDisplayString(0, "Hello World!!");
  wait1Msec(1000);
  nxtDisplayString(0, "IRSensor value");
  nxtDisplayString(2, "TouchSensor value");
  nxtDisplayString(4, "SonarSensor value");
  nxtDisplayString(6, "LightSensor value");
  //nxtDisplayString(4, "Encoder value");
  while (true) {
    nxtDisplayString(1, "%03d", SensorValue[IR]);
    nxtDisplayString(3, "%d", SensorValue[TOUCH]);
    nxtDisplayString(5, "%d", SensorValue[SONAR]);
    nxtDisplayString(7, "%d", SensorValue[LIGHT]);
    //nxtDisplayString(5, "%d", nMotorEncoder[motorA]);
  }
}
